fastai/fastai2

- fastai2/vision/data.py
- nbs/09a_vision_data.ipynb
Apply the changes discussed in #1 
I tried doing the change in a more compact way. The other approach would be to do `axs = axs[:n]` after line 79.
Let me know if you think that is a better idea.
> Fixes get_grid size mismatch bug

- fastai2/layers.py
- nbs/03a_layers.ipynb
`_get_norm` was raising an error when `affine=False` because `bn.weight` is `None`. We should only initialize weights if `affine=True`.
> fixes norm init

- fastai2/layers.py
- nbs/03a_layers.ipynb
Calling `in_channels` would fail if the first layer was a `Batch/Instance Norm` layer because this layers have an attribute called `weight`. If `affine=True` then the error was raised:
```python
~/forks/fastai2/fastai2/layers.py in in_channels(m)
563     "Return the shape of the first weight layer in `m`."
564     for l in flatten_model(m):
--> 565         if hasattr(l, 'weight'): return l.weight.shape[1]
566     raise Exception('No weight layer')
IndexError: tuple index out of range
```
If `affine=False` the layer would still have `weight` but it would be None. One way of solving the issue would be to assert that the layer we are testing is a constitutional layer, but I found that would be too restrictive, maybe the user implements his own ConvLayer. So I check that the weights should …
> fixes in_channels

- fastai2/data/load.py
- nbs/02_data.load.ipynb
Just an added an error when batch size is bigger than dataset. A bit more helpful for debugging. Tested with:
from fastai2.basics import *
from fastai2.vision.all import *
from fastai2.callback.all import *
data = DataBlock(blocks=(ImageBlock, CategoryBlock), 
get_items=get_image_files, 
splitter=RandomSplitter(),
get_y=parent_label)
path = untar_data(URLs.DOGS)
bunch = data.databunch(path/"sample", item_tfms=RandomResizedCrop(460), bs=32, batch_tfms=[*aug_transforms(size=299, max_warp=0), Normalize.from_stats(*imagenet_stats)])
bunch.show_batch()
> batchsize error

- fastai2/callback/hook.py
- nbs/15_callback.hook.ipynb
I found this bug when I tried to print the summary from model that includes nn.GRU(). It would throw error: `TypeError: unsupported format string passed to list.__format__ ` 
Dig into the code and I find that _print_shapes() will produce list of string for multiple outputs but this formated string f'{_print_shapes(sz, bs):<20}' in summary() needs a single string. 
Fix it by just let _print_shapes() return string and limit its length for display.
Also add a test that check it will not break when the model has multiple outputs.
When I tried to fix this bug, I found another issue. If the output batch size is not at first dimension like nn.GRU() by default, it will return a wrong size. No good idea for solving this.
> fix learn.summary for multiple outputs

- README.md
- docs/index.html
- nbs/index.ipynb
The existing command in the README for an editable install is: `pip install -e .[dev]`.
This does not work in the `zsh` shell. And since MacOS is now defaulting to `zsh` it becomes important for it to work with it as well.
Changing it to: `pip install -e ".[dev]"` makes it work with *both* `bash` and `zsh` (on ubuntu, macOS *and* Windows).
This GitHub issue adds more light into the issue and it's potential solutions: https://github.com/mu-editor/mu/issues/852. 
This comment concludes that adding double quotes is a universal solution for most platforms and shells: https://github.com/mu-editor/mu/issues/852#issuecomment-499870171
(P.S.: This is my 2nd PR on GitHub... apologies if I have violated any *recommended* ways to make a PR 😅)
> Fixed editable install command to work universally with most shells

- fastai2/distributed.py
- nbs/20a_distributed.ipynb
fixes the distributed training issue introduces with the change from a `Cuda` callback to a `device` parameter on DataLoader reported in #57 and [here](https://forums.fast.ai/t/distributed-training-fails/63102) in the forums.
The fix is simply passing the `device` parameter from the `DataLoader` to the `DistributedDL` when it is initialized.
Also fixes this error:
```
warn(f"You are setting an attribute ({name}) that also exists in the learner. Please be advised that you're not setting it in the learner but in the callback. Use `self.learn.{name}` if you would like to change it in the learner.")
/home/jaidmin/Software/Devel/forks/fastai2/fastai2/learner.py:30: UserWarning: You are setting an attribute (dl) that also exists in the learner. Please be advised that you're not setting it in …
```
> fix distributed training after DataLoader change (device parameter)

- fastai2/text/models/awdlstm.py
- nbs/32_text.models.awdlstm.ipynb
Bug happened when I called `AWD_QRNN` with `bidir=True`, it would cause this error: `"Can't save the previous X with bidirectional."`
I think the problem is AWD_QRNN always use save_prev_x=True to call QRNN, no matter bidir is what.
Fix it by assign flip of bidir to save_prev_x and add 2 simple tests.
> fix AWD_QRNN when bidir=True

- fastai2/callback/wandb.py
- nbs/70_callback.wandb.ipynb
This PR:
* fixes #70 
* allow logging any dict for more flexibility -> we can improve `wandb_process` later
* log `best/worst predictions`
* separate `inputs`, `labels`, `predictions` to display them separately or together. This also let us display evolution of predictions along time (this is what I'm currently doing)
* allow custom `wandb_process` for users to log whatever they want
> WandbCallback: fix issues

- fastai2/data/block.py
- nbs/06_data.block.ipynb
Looks like this was inadvertently removed in https://github.com/fastai/fastai2/commit/dcc7e1bfa7170700143127e56d8dae8e97ef8177#diff-3fec432759d383a373137d69c9ac4c72L58?
> fix: DataBlock respect dl_type kwarg

- fastai2/text/core.py
- nbs/30_text.core.ipynb
When calling Tokenizer.from_df, rules=rules lies inside the call to get_tokenizer and so the Tokenizer class defaults to the default fastai rules as the class cannot see any fules added in .from_df()
> Show rules to Tokenizer calss in .from_df

- nbs/07_vision.core.ipynb
I noticed that the convention [changed](https://github.com/fastai/fastai2/blob/master/fastai2/vision/core.py#L175) from v1 to x1,y1,x2,y2.
> fix bbox coordinates convention

- fastai2/data/block.py
- nbs/06_data.block.ipynb
This fixes an issue with `DataBlock.summary` which was introduced with the removal of the `Cuda` transform. 
It's simply fixed by moving the batch to the device that the dataloader (and therefore the transforms expect). 
Another way would be to make Normalize agnostic and just work with the input regardless on what device its on.
Here is the issue when trying to call `summary` (the issue appears if there is a `Normalize` in the `batch_tfms` transforms)
```Setting-up type transforms pipelines
Collecting items from /home/jaidmin/.fastai/data/mnist_tiny
Found 1428 items
2 datasets of sizes 709,699
Setting up Pipeline: PILBase.create
Setting up Pipeline: parent_label -> Categorize
Building one sample
Pipeline: PILBase.create
starting from
/home/jaidmin/.fastai/data/mnist_tiny/train/7/8717.png …
```
> fix datablock.summary device error if normalize is a batch_tfm

- fastai2/text/models/awdlstm.py
- nbs/32_text.models.awdlstm.ipynb
Error: `rnn: hx is not contiguous`
This error happens when 
1. bidir=True 
2. bs decrease
3. run on gpu
The 1 and 2 cause `self.hidden[l][0][:,:bs]` be not contiguous, and with 3 the error happens.
Fix it by adding contiguous() after self.hidden[l][0][:,:bs] and add a test that can reproduce this error with cuda flag.
> fix AWD_LSTM not contiguous bug

- nbs/10_tutorial.pets.ipynb
There was still one reference to `Datasource`, so I changed it to use the new name `Datasets`.
> Small fix to 10_tutorial.pets notebook

- nbs/course/lesson3-imdb.ipynb
Two cahnges:
**1: Make use of `is_valid` column of original dataframe**
from:
```python
dbunch_lm = TextDataLoaders.from_df(df, text_col='text', label_col='label', 
path=path, is_lm=True)
```
to:
```python
dbunch_lm = TextDataLoaders.from_df(df, text_col='text', label_col='label', 
path=path, is_lm=True, valid_col='is_valid')
```
Actually the count of validation items does not change (the default valid_pct=20% that takes to 200 items), but no more sampling randomness is present:
```Python
df.is_valid.value_counts()
False    800
True     200
```
**2: updated method name to `plot_lr_find``**
Renamed method to new convention, from:
```Python
learn.recorder.plot(skip_end=15)
```
to:
```Python
learn.recorder.plot_lr_find(skip_end=15)
```
> Fix lesson3-imdb

- fastai2/medical/imaging.py
As commented [here](https://forums.fast.ai/t/deployment-dicom-images/66288) deployment with ipywidgets returns `bytes`. In order to make `PILDicom.create` to manage it, an instance on `PILDicom` class is added.
> PILDicom accepts bytes as input

- nbs/course/lesson7-human-numbers.ipynb
Fix for the below error in lessson7-human-numbers.py
Fix: def reset(self): self.h = torch.zeros(bs, nh).cuda()
> AttributeError: 'Model3' object has no attribute 'f'

- .github/workflows/main.yml
A bit of GitHub Actions maintenance.
- Update to [checkout](https://github.com/actions/checkout) v2 (performs faster)
- Update to [setup-python](https://github.com/actions/setup-python) v2
- Use Python 3.8 (latest stable version)
> GitHub Actions: Update checkout and setup-python, use Python 3.8

- fastai2/callback/cutmix.py
- nbs/74_callback.cutmix.ipynb
x1,y1,x2,y2,w,h are all integers, so division by W*H always results in 0.0, and so lerp amount is always 1.
> Fix CutMix lerp weight bug

- fastai2/text/data.py
- nbs/31_text.data.ipynb
When I was working on my LetterTokenizer, I have noticed `seq_len` parameter of `TextBlock` is ignored if `is_lm` is set to True:
```
text_block = TextBlock(tok_tfm=tkn2, is_lm=True, seq_len=50).from_folder(path=path, is_lm=True, seq_len=50)
dls = DataBlock(
blocks=blocks,
get_items=get_text_files,
get_y=None,
splitter=splitter).dataloaders(path)
t = first(dls.train)[0][0]
print(len(t))  ## prints 72 which is the default parameter
```
I have verified that the problem is fixed is I use a modified version of `TextBlock` where `seq_len` is propagated as follows (the only difference is on line 6, setting `dls_kwargs={'seq_len': seq_len}` instead `dls_kwargs={}`)
```
class MyTextBlock(TransformBlock):
"A `TransformBlock` for texts"
@delegates(Numericalize.__init__)
def __init__(self, tok_tfm, …
```
> Fixing TextBlock not passing seq_len argument when is_lm is True

- fastai2/interpret.py
- nbs/20_interpret.ipynb
**Problem:** A Dataloader's vocab can be an integer type. When calling `ClassificationInterpretation.print_classification_report()` out to `sklearn.classification_report()` sklearn expects the target label names to be strings, resulting in an exception being thrown here: (because integers have no `len` property)
```
name_width = max(len(cn) for cn in target_names)
```
**Fix:** use vocab converted to string when calling this function: 
This kaggle notebook reproduces the problem on a simple example: https://www.kaggle.com/stillsut/fastai2-repro-1/
- it works on MNIST when vocab is already a string
- it fails on MNIST when vocab is an integer, this happens naturally when the source of the dataloader is a dataframe where the label is an integer type.
- also shows that this PR fixes the …
> Pass vocab as string when calling sklearn classification report

- fastai2/vision/augment.py
Extend `Zoom` transform with zoom out capabilities with `min_zoom`
RandomRsizedCrop needs at least order==1 to run after PointScaler
Resize.final_size is not used, so I removed it for code clarity
> Vision transforms improvements

- fastai2/callback/progress.py
I think this is a similar issue to #156 -- I get the same error about the Learner missing a Recorder if I'm using `ShowGraphCallback` with `SaveModelCallback` (and `WandbCallback`).
> ShowGraphCallback needs remove_on_fetch=True

- fastai2/vision/augment.py
`crop_pad` failed for TensorPoint in the situation where `orig_sz` or `tl` are `None` because `TensorPoint` has no `size` attribute (which happens in `RandomResizeCrop.encodes` for validation split)
I also extened `_get_sz` to search additionally for `sz` meta (which I think is set during casting to TensorPoint). This happens when calling `crop_pad` twice in a row, which is the case in `RandomResizeCrop.encodes` for validation split (somewhat related to issue https://github.com/fastai/fastai2/issues/373)
> crop_pad improvements for TensorPoint

- nbs/30_text.core.ipynb
The SentencePiece tokenizer currently refers to Spacy' in the docstring instead of SentencePiece. This isn't a huge deal but might cause some confusion.
> Small fix to docstring for the SentencePiece tokenizer

- fastai2/vision/augment.py
F.interpolate, used by the RatioResize transform in fastai2’s batch image augmenter, changed it’s default behaviour between pytorch versions v1.4.0 and v1.5.0, causing installations using pytorch v1.5.0 (such as google colab) to throw a warning that using F.interpolate in this way will fail in future. Adding the argument “recompute_scale_factor=True” when calling F.interpolate prevents pytorch from throwing this warning, and ensures fastai compatibility with future versions of pytorch.
> F.interpolate compatability patch for pytorch 1.5.0

- fastai2/interpret.py
- nbs/20_interpret.ipynb
I encountered this error while calling **ClassificationInterpretation.print_classification_report()**
```
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py in classification_report(y_true, y_pred, labels, target_names, sample_weight, digits, output_dict, zero_division)
1993                 "Number of classes, {0}, does not match size of "
1994                 "target_names, {1}. Try specifying the labels "
-> 1995                 "parameter".format(len(labels), len(target_names))
1996             )
1997     if target_names is None:
ValueError: Number of classes, 23, does not match size of target_names, 25. Try specifying the labels parameter
```
By my understanding, while fastai2 does pass the label names to **sklearn.metrics.classification_report()**, sklearn is …
> sklearn classification report: pass label list

- fastai2/text/data.py
- nbs/31_text.data.ipynb
Adds additional documentation for SortedDL to emphasise the benefit of passing res to the dataloader
> Additional SortedDL documentation

- .github/workflows/main.yml
We have to instruct GitHub Actions to pull the HEAD of the PR because the default is to pull [the last commit on the base branch that the PR was based on!](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target).  
Something to pay attention to @jph00
> Update Actions Workflow To Pull The Right Contents When Running Tests

- .github/workflows/main.yml
This is where we try to supply the data to the CI jobs.  Everything has been split into 3 batches.
@jph00 This is probably the most advanced Action I have ever written attempting to leverage [caching](https://docs.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows#using-the-cache-action) as well as [artifacts](https://docs.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts#:~:text=GitHub%20provides%20two%20actions%20that,data%20before%20the%20job%20ends.) as a backup incase caching doesn't work
> Optionally download data in CI
